version: '3'
services:
  postgres:
    container_name: "project-postgres"
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=500'
  api:
    container_name: "project-api"
    build:
      context: .
    volumes:
      - ../golang-rest-project-starter:/app
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      PORT: 4000

volumes:
  pg-data:
