// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Note: All text outside function is considered comments
//

//line tml/index.qtpl:3
package tml

//line tml/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line tml/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line tml/index.qtpl:3
func StreamCompile(qw422016 *qt422016.Writer, alerts []string) {
//line tml/index.qtpl:3
	qw422016.N().S(`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Alarms</title>
  </head>
  <body>
    <h1>Alarms</h1>
    <ul>
      `)
//line tml/index.qtpl:13
	if len(alerts) == 0 {
//line tml/index.qtpl:13
		qw422016.N().S(`
        <p>No alarms at this time.</p>
      `)
//line tml/index.qtpl:15
	}
//line tml/index.qtpl:15
	qw422016.N().S(`
      `)
//line tml/index.qtpl:16
	for i, alert := range alerts {
//line tml/index.qtpl:16
		qw422016.N().S(`
        <li>`)
//line tml/index.qtpl:17
		qw422016.N().D(i)
//line tml/index.qtpl:17
		qw422016.N().S(` -- `)
//line tml/index.qtpl:17
		qw422016.E().S(alert)
//line tml/index.qtpl:17
		qw422016.N().S(`</li>
      `)
//line tml/index.qtpl:18
	}
//line tml/index.qtpl:18
	qw422016.N().S(`
    </ul>
  </body>
</html>
`)
//line tml/index.qtpl:22
}

//line tml/index.qtpl:22
func WriteCompile(qq422016 qtio422016.Writer, alerts []string) {
//line tml/index.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tml/index.qtpl:22
	StreamCompile(qw422016, alerts)
//line tml/index.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line tml/index.qtpl:22
}

//line tml/index.qtpl:22
func Compile(alerts []string) string {
//line tml/index.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line tml/index.qtpl:22
	WriteCompile(qb422016, alerts)
//line tml/index.qtpl:22
	qs422016 := string(qb422016.B)
//line tml/index.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line tml/index.qtpl:22
	return qs422016
//line tml/index.qtpl:22
}
