// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!DOCTYPE html>
// <html>
//   <head>
//     <meta charset="utf-8">
//     <title>Alarms</title>
//   </head>
//   <body>
//     <h1>Alarms</h1>
//

//line tml/index.qtpl:9
package tml

//line tml/index.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line tml/index.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line tml/index.qtpl:9
func StreamCompile(qw422016 *qt422016.Writer, alerts []string) {
//line tml/index.qtpl:9
	qw422016.N().S(`
    	 <ul>
            `)
//line tml/index.qtpl:11
	for i, alert := range alerts {
//line tml/index.qtpl:11
		qw422016.N().S(`
                <li>`)
//line tml/index.qtpl:12
		qw422016.N().D(i)
//line tml/index.qtpl:12
		qw422016.N().S(` -- `)
//line tml/index.qtpl:12
		qw422016.E().S(alert)
//line tml/index.qtpl:12
		qw422016.N().S(`</li>
            `)
//line tml/index.qtpl:13
	}
//line tml/index.qtpl:13
	qw422016.N().S(`
            </ul>
    `)
//line tml/index.qtpl:15
}

//line tml/index.qtpl:15
func WriteCompile(qq422016 qtio422016.Writer, alerts []string) {
//line tml/index.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tml/index.qtpl:15
	StreamCompile(qw422016, alerts)
//line tml/index.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line tml/index.qtpl:15
}

//line tml/index.qtpl:15
func Compile(alerts []string) string {
//line tml/index.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line tml/index.qtpl:15
	WriteCompile(qb422016, alerts)
//line tml/index.qtpl:15
	qs422016 := string(qb422016.B)
//line tml/index.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line tml/index.qtpl:15
	return qs422016
//line tml/index.qtpl:15
}

//   </body>
// </html>
